# This is all the default fields on rustfmt

# Misc
color = "Auto"
disable_all_formatting = false
edition = "2015"
emit_mode = "Files"
error_on_line_overflow = false
error_on_unformatted = false
ignore = []
make_backup = false
required_version = "1.8.0"
show_parse_errors = true
skip_children = false
style_edition = "2024"
unstable_features = true
version = "One"

# Comments
normalize_comments = true
normalize_doc_attributes = false
format_code_in_doc_comments = false

# Definitions
enum_discrim_align_threshold = 100
fn_params_layout = "Vertical"
force_explicit_abi = false
merge_derives = false
reorder_modules = false
reorder_impl_items = true
struct_field_align_threshold = 100

# Generated files (Uncommon)
format_generated_files = true
generated_marker_line_search_limit = 5

# Imports
imports_indent = "Block"
imports_layout = "Mixed"
imports_granularity = "Item"
merge_imports = false
group_imports = "One"
reorder_imports = false

# Indent
hard_tabs = true
tab_spaces = 8
indent_style = "Visual"

# Macros
format_macro_matchers = true
format_macro_bodies = true
skip_macro_invocations = []

# Newlines
blank_lines_upper_bound = 3
blank_lines_lower_bound = 1
combine_control_expr = true
empty_item_single_line = true
fn_single_line = true
force_multiline_blocks = true
newline_style = "Windows"
overflow_delimited_expr = false
use_small_heuristics = "Max"
struct_lit_single_line = true
where_single_line = false
wrap_comments = true

# Punctuation
binop_separator = "Back"
brace_style = "SameLineWhere"
condense_wildcard_suffixes = false
control_brace_style = "AlwaysNextLine"
match_block_trailing_comma = false
remove_nested_parens = false
space_before_colon = true
space_after_colon = true
spaces_around_ranges = true
trailing_semicolon = false
trailing_comma = "Vertical"
type_punctuation_density = "Compressed"
use_try_shorthand = false

# Widths
array_width = 60
attr_fn_like_width = 70
chain_width = 60
comment_width = 10
doc_comment_code_block_width = 100
fn_call_width = 1
inline_attribute_width = 0
max_width = 1000
struct_lit_width = 18
struct_variant_width = 35
single_line_if_else_max_width = 1000
single_line_let_else_max_width = 1000

# Other
format_strings = false
hex_literal_case = "Preserve"
short_array_element_width_threshold = 20
match_arm_blocks = true
match_arm_leading_pipes = "Never"
use_field_init_shorthand = false
