# This is all the default fields on rustfmt

# Misc
color = "Auto"
disable_all_formatting = false
edition = "2015"
emit_mode = "Files"
error_on_line_overflow = false
error_on_unformatted = false
ignore = []
make_backup = false
required_version = "1.8.0"
show_parse_errors = true
skip_children = false
style_edition = "2015"
unstable_features = false
version = "One"

# Comments
normalize_comments = false
normalize_doc_attributes = false
format_code_in_doc_comments = false

# Definitions
enum_discrim_align_threshold = 0
fn_params_layout = "Tall"
force_explicit_abi = true
merge_derives = true
reorder_modules = true
reorder_impl_items = true
struct_field_align_threshold = 0

# Generated files (Uncommon)
format_generated_files = true
generated_marker_line_search_limit = 5

# Imports
imports_indent = "Block"
imports_layout = "Mixed"
imports_granularity = "Preserve"
group_imports = "Preserve"
reorder_imports = true

# Indent
hard_tabs = false
tab_spaces = 4
indent_style = "Block"

# Macros
format_macro_matchers = false
format_macro_bodies = true
skip_macro_invocations = []

# Newlines
blank_lines_upper_bound = 1
# NOTE: This [blank_lines_lower_bound] will be limited to 3,
# any participation with a value greater than 3 will be ignored 
blank_lines_lower_bound = 0
combine_control_expr = true
empty_item_single_line = true
fn_single_line = false
force_multiline_blocks = false
newline_style = "Auto"
overflow_delimited_expr = false
use_small_heuristics = "Default"
struct_lit_single_line = true
where_single_line = false
wrap_comments = false

# Punctuation
binop_separator = "Front"
brace_style = "SameLineWhere"
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
match_block_trailing_comma = false
remove_nested_parens = true
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
trailing_semicolon = true
trailing_comma = "Vertical"
type_punctuation_density = "Wide"
use_try_shorthand = false

# Widths
array_width = 60
attr_fn_like_width = 70
chain_width = 60
comment_width = 80
doc_comment_code_block_width = 100
fn_call_width = 60
inline_attribute_width = 0
max_width = 100
struct_lit_width = 18
struct_variant_width = 35
single_line_if_else_max_width = 50
single_line_let_else_max_width = 50

# Other
format_strings = false
hex_literal_case = "Preserve"
short_array_element_width_threshold = 10
match_arm_blocks = true
match_arm_leading_pipes = "Never"
use_field_init_shorthand = false
