# This is all the default fields on rustfmt

# Misc
color = "Auto"
disable_all_formatting = false
edition = "2021"
error_on_line_overflow = false
ignore = []
make_backup = false
unstable_features = false

# Comments
normalize_comments = false
normalize_doc_attributes = false
format_code_in_doc_comments = true

# Definitions
fn_params_layout = "Compressed"
force_explicit_abi = false
merge_derives = false
reorder_modules = false
reorder_impl_items = false
struct_field_align_threshold = 0

# Generated files (Uncommon)
format_generated_files = false
generated_marker_line_search_limit = 0

# Imports
imports_indent = "Block"
imports_layout = "Mixed"
imports_granularity = "Preserve"
group_imports = "Preserve"
reorder_imports = true

# Indent
hard_tabs = false
tab_spaces = 0
indent_style = "Block"

# Macros
format_macro_matchers = false
format_macro_bodies = true
skip_macro_invocations = []

# Newlines
combine_control_expr = false
empty_item_single_line = false
fn_single_line = true
force_multiline_blocks = false
newline_style = "Auto"
overflow_delimited_expr = false
use_small_heuristics = "Default"
struct_lit_single_line = true
where_single_line = true
wrap_comments = true

# Punctuation
binop_separator = "Back"
brace_style = "PreferSameLine"
condense_wildcard_suffixes = false
control_brace_style = "ClosingNextLine"
match_block_trailing_comma = false
remove_nested_parens = true
space_before_colon = false
space_after_colon = false
spaces_around_ranges = false
trailing_semicolon = false
trailing_comma = "Never"
type_punctuation_density = "Compressed"
use_try_shorthand = false

# Widths
array_width = 100
attr_fn_like_width = 100
chain_width = 100
comment_width = 100
doc_comment_code_block_width = 100
fn_call_width = 100
inline_attribute_width = 100
max_width = 100
struct_lit_width = 100
struct_variant_width = 100
single_line_if_else_max_width = 100
single_line_let_else_max_width = 100

# Other
format_strings = false
hex_literal_case = "Preserve"
short_array_element_width_threshold = 10
match_arm_blocks = false
match_arm_leading_pipes = "Preserve"
use_field_init_shorthand = false
