# 🚨 Peor configuración posible de rustfmt 🚨

# Misc
color = "Never"
disable_all_formatting = false
edition = "2015"
emit_mode = "Files"
error_on_line_overflow = false
error_on_unformatted = false
make_backup = true
required_version = "1.8.0"
show_parse_errors = true
skip_children = true
style_edition = "2015"
unstable_features = true
version = "One"

# Comments
normalize_comments = false
normalize_doc_attributes = false
format_code_in_doc_comments = false
wrap_comments = false

# Definitions
enum_discrim_align_threshold = 100
fn_params_layout = "Compressed"
force_explicit_abi = true
merge_derives = false
reorder_modules = true
reorder_impl_items = true
struct_field_align_threshold = 100

# Generated files
format_generated_files = true
generated_marker_line_search_limit = 0

# Imports
imports_indent = "Visual"
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
group_imports = "One"
reorder_imports = true

# Indent
hard_tabs = true
tab_spaces = 3
indent_style = "Visual"

# Macros
format_macro_matchers = true
format_macro_bodies = false
skip_macro_invocations = ["println", "dbg"]

# Newlines
blank_lines_upper_bound = 10
blank_lines_lower_bound = 3
combine_control_expr = false
empty_item_single_line = false
fn_single_line = true
force_multiline_blocks = true
newline_style = "Unix"
overflow_delimited_expr = true
use_small_heuristics = "Off"
struct_lit_single_line = false
where_single_line = true

# Punctuation
binop_separator = "Back"
brace_style = "AlwaysNextLine"
condense_wildcard_suffixes = false
control_brace_style = "AlwaysNextLine"
match_block_trailing_comma = false
remove_nested_parens = false
space_before_colon = true
space_after_colon = false
spaces_around_ranges = true
trailing_semicolon = false
trailing_comma = "Never"
type_punctuation_density = "Compressed"
use_try_shorthand = false

# Widths (ridículos a propósito)
array_width = 5
attr_fn_like_width = 10
chain_width = 15
comment_width = 20
doc_comment_code_block_width = 15
fn_call_width = 10
inline_attribute_width = 0
max_width = 30
struct_lit_width = 5
struct_variant_width = 10
single_line_if_else_max_width = 0
single_line_let_else_max_width = 0

# Other
format_strings = false
hex_literal_case = "Upper"
short_array_element_width_threshold = 1
match_arm_blocks = false
match_arm_leading_pipes = "Always"
use_field_init_shorthand = false
