# This is all the default fields on rustfmt
# Definitions
enum_discrim_align_threshold = 20
fn_params_layout = "Vertical"
force_explicit_abi = false
merge_derives = true
reorder_modules = false
reorder_impl_items = false
struct_field_align_threshold = 100

# Imports
imports_indent = "Block"
imports_layout = "Mixed"
imports_granularity = "Preserve"
group_imports = "One"
reorder_imports = false

# Indent
hard_tabs = true
tab_spaces = 50
indent_style = "Block"

# Macros
format_macro_matchers = false
format_macro_bodies = false

# Newlines
blank_lines_upper_bound = 500
blank_lines_lower_bound = 500
combine_control_expr = true
empty_item_single_line = false
fn_single_line = true
force_multiline_blocks = true
newline_style = "Windows"
overflow_delimited_expr = true
where_single_line = false
wrap_comments = false

# Punctuation
binop_separator = "Front"
brace_style = "AlwaysNextLine"
condense_wildcard_suffixes = false
control_brace_style = "AlwaysNextLine"
match_block_trailing_comma = false
remove_nested_parens = false
space_before_colon = false
space_after_colon = false
spaces_around_ranges = false
trailing_semicolon = true
trailing_comma = "Never"
type_punctuation_density = "Compressed"
use_try_shorthand = false

# Widths
array_width= 5000
attr_fn_like_width= 5000
chain_width= 5000
comment_width= 5000
doc_comment_code_block_width= 5000
fn_call_width= 5000
inline_attribute_width= 5000
max_width= 5000
struct_lit_width= 5000
struct_variant_width= 5000
single_line_if_else_max_width= 5000
single_line_let_else_max_width= 5000

# Other
format_strings = false
short_array_element_width_threshold= 5000
match_arm_blocks = false